# Generated by Django 2.2.10 on 2020-03-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20200319_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image'),
        ),
    ]
