# -*- coding: utf-8 -*-
# Generated by Django 2.1.5 on 2020-03-14 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', null=True, verbose_name='content')),
                ('score', models.IntegerField(verbose_name='score')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='title')),
                ('detail', models.TextField(default='', null=True, verbose_name='Description')),
                ('pic', models.ImageField(upload_to='image', verbose_name='pic')),
                ('actor', models.CharField(max_length=512, verbose_name='Actors')),
                ('duration', models.IntegerField(verbose_name='duration')),
                ('publish_time', models.DateTimeField(verbose_name='publish_time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classify', to='myapp.ClassifyModel', verbose_name='classify')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
            },
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tie_comment', to='myapp.MovieModel', verbose_name='评论的帖子'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
    ]
