# -*- coding: utf-8 -*-
# Generated by Django 2.1.5 on 2020-03-14 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifymodel',
            options={'verbose_name': 'genres', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='moviemodel',
            options={'verbose_name': 'movies', 'verbose_name_plural': 'movies'},
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='star',
            field=models.IntegerField(default=1, verbose_name='star'),
            preserve_default=False,
        ),
    ]
