# Generated by Django 2.1.5 on 2020-03-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190314_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='score',
            field=models.FloatField(default=4, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='publish_time',
            field=models.DateTimeField(verbose_name='Publish Time'),
        ),
    ]
