# Generated by Django 2.1.5 on 2020-03-19 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20200316_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavorateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Colection time')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='classifymodel',
            options={'verbose_name': 'Movie Type', 'verbose_name_plural': 'Movie Type'},
        ),
        migrations.AlterModelOptions(
            name='moviemodel',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movie'},
        ),
        migrations.AlterField(
            model_name='classifymodel',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='content',
            field=models.TextField(default='', null=True, verbose_name='Comment context'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Comment Time'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tie_comment', to='myapp.MovieModel', verbose_name='Comment page'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comment User'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classify', to='myapp.ClassifyModel', verbose_name='Classify'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='detail',
            field=models.TextField(default='', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='duration',
            field=models.IntegerField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='pic',
            field=models.ImageField(upload_to='image', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='publish_time',
            field=models.DateTimeField(verbose_name='Publ'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='star',
            field=models.FloatField(verbose_name='Rate'),
        ),
        migrations.AddField(
            model_name='favoratemodel',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.MovieModel', verbose_name='movie'),
        ),
        migrations.AddField(
            model_name='favoratemodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Colectioner'),
        ),
    ]
